FROM nginx:1.27.3-alpine
#ARG JAR_FILE=targelt/*.jar
COPY config/nginx.conf /etc/nginx/conf.d/default.conf
#COPY ${JAR_FILE} ROOT.jar
#ENTRYPOINT ["java","-jar","/ROOT.jar"]
#CMD ["nginx", "-g", "daemon off;"]
